---
- name: Prepare PostgreSQL Cluster VM Storage
  hosts: postgres_cluster
  become: true
  become_method: sudo
  gather_facts: true
  any_errors_fatal: true
  
  vars:
    disk_configurations:
      - device: nvme0n2
        expected_size: "256G"
        mount_point: "/mnt/pgdata"
        filesystem: ext4
        owner: postgres
        group: postgres
      - device: nvme0n3
        expected_size: "64G"
        mount_point: "/mnt/pgwal"
        filesystem: ext4
        owner: postgres
        group: postgres
      - device: nvme0n4
        expected_size: "32G"
        mount_point: "/mnt/etcd"
        filesystem: ext4
        owner: postgres
        group: postgres
  
  tasks:
    - name: Check if postgres user exists
      ansible.builtin.getent:
        database: passwd
        key: postgres
      register: postgres_user_check
      ignore_errors: true
      check_mode: false

    - name: Create postgres user if it doesn't exist
      ansible.builtin.user:
        name: postgres
        system: true
        shell: /bin/bash
        home: /var/lib/postgresql
        createhome: true
        state: present
      when: postgres_user_check.failed | default(false)

    - name: Process each disk configuration
      include_tasks: disk_setup_tasks.yml
      loop: "{{ disk_configurations }}"
      loop_control:
        loop_var: disk_config

- name: Create disk setup tasks file
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Ensure tasks directory exists
      ansible.builtin.file:
        path: "{{ playbook_dir }}"
        state: directory
      delegate_to: localhost
      run_once: true